name: Build and Deploy Client to GitHub Pages
on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: echo "VITE_API_URL=${{ secrets.API_URL }}" > .env.production
      - run: npm run build
      - run: node scripts/spa-404.mjs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: client/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
